# Generated by Django 3.0.8 on 2020-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(related_name='restaurants', to='food.Cuisine'),
        ),
    ]
