# Generated by Django 3.0.8 on 2020-07-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200716_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nick',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
