# Generated by Django 3.0.8 on 2020-07-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200717_0604'),
        ('food', '0003_restaurant_nick'),
    ]

    operations = [
    ]
