# Generated by Django 3.0.5 on 2020-07-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_merge_20200717_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='cost',
            new_name='price',
        ),
    ]
