# Generated by Django 3.0.5 on 2020-07-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200718_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='pizza', max_length=50),
            preserve_default=False,
        ),
    ]
