# Generated by Django 3.0.8 on 2020-07-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200718_0848'),
        ('food', '0007_auto_20200718_1713'),
    ]

    operations = [
    ]
