# Generated by Django 3.0.8 on 2020-07-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_menuitem_category'),
        ('food', '0007_auto_20200718_1713'),
    ]

    operations = [
    ]
