# Generated by Django 3.0.5 on 2020-07-20 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0010_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='food.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='food.MenuItem')),
                ('orderList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.OrderList')),
            ],
        ),
    ]
