# Generated by Django 3.0.5 on 2020-07-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20200720_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
