# Generated by Django 3.0.5 on 2020-07-20 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0014_orderlist_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
