# Generated by Django 3.0.5 on 2020-07-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20200720_0527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderItem',
        ),
    ]
