# Generated by Django 3.0.5 on 2020-07-20 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0016_auto_20200720_0529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderList',
            new_name='Order',
        ),
    ]
