# Generated by Django 3.0.5 on 2020-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_auto_20200720_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
