# Generated by Django 3.0.5 on 2020-07-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ownedRestaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='food.Restaurant'),
        ),
    ]
