# Generated by Django 3.0.5 on 2020-07-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_profile_ownedrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmedTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveredTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
