# Generated by Django 3.0.8 on 2020-08-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_auto_20200730_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='woodstock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
