# Generated by Django 3.1 on 2020-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_restaurant_ordertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalSpent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='averageCost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='averageOrderTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='totalOrderCount',
            field=models.IntegerField(default=0),
        ),
    ]
