# Generated by Django 3.1.1 on 2020-09-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_auto_20200826_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default='', max_length=64),
        ),
    ]
